.TH "blast_filtering.h" 3 "Sat Dec 31 2011" "Version 0.9.7.6" "turboOrtho" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blast_filtering.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '../cmd_line/cmd_list.h'\fP
.br
\fC#include '../configure.h'\fP
.br
\fC#include '../log_builder/log_builder.h'\fP
.br
\fC#include '../internal_blast/taxa.h'\fP
.br
\fC#include '../internal_blast/id_simil_list.h'\fP
.br
\fC#include '../internal_blast/list_file_parse.h'\fP
.br
\fC#include '../internal_blast/list_file_struct.h'\fP
.br
\fC#include '../internal_blast/enum_mcl.h'\fP
.br
\fC#include '../blast_parsing/bp_container.h'\fP
.br
\fC#include 'pipe_bucket.h'\fP
.br
\fC#include 'pipe_binary.h'\fP
.br
\fC#include 'pipe_merge.h'\fP
.br
\fC#include 'pipe_norm.h'\fP
.br
\fC#include 'pipe_write.h'\fP
.br
\fC#include 'pipe_struct.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBblast_filtering\fP"
.br
.RI "\fIProduces a filtered output of the input. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef class \fBblast_filtering\fP \fBblast_filtering_t\fP"
.br
.RI "\fIProduces a filtered output of the input. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for turboOrtho from the source code.
