.TH "blast_filtering_main.h" 3 "Sat Dec 31 2011" "Version 0.9.7.6" "turboOrtho" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blast_filtering_main.h \- 
.PP
The launcher of the filtering library.  

.SH SYNOPSIS
.br
.PP
\fC#include '../configure.h'\fP
.br
\fC#include 'blast_filtering.h'\fP
.br
\fC#include 'cmd_list.h'\fP
.br

.SH "Detailed Description"
.PP 
The launcher of the filtering library. 

\fBAuthor:\fP
.RS 4
Ole Kristian Ekseth (oekseth) 
.RE
.PP
\fBDate:\fP
.RS 4
31.12.2011 by oekseth (initial) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for turboOrtho from the source code.
