.TH "enum_write_list_t.h" 3 "Sat Dec 31 2011" "Version 0.9.7.6" "turboOrtho" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enum_write_list_t.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBwrite_list\fP \fBwrite_list_t\fP"
.br
.RI "\fIIn order to identify the files. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBwrite_list\fP { \fBblast_ortho_pairs_list_numbers\fP, \fBblast_inparalog_list_numbers\fP, \fBblast_complete_list_numbers\fP, \fBblast_ortho_relations_list_numbers\fP }"
.br
.RI "\fIIn order to identify the files. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const uint \fBsize_write_list_t\fP = 4"
.br
.RI "\fIThe number of elements in the enum write_list. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for turboOrtho from the source code.
