.TH ""Algorithms for serial Filtering"" 3 "Sat Dec 31 2011" "Version 0.9.7.6" "turboOrtho" \" -*- nroff -*-
.ad l
.nh
.SH NAME
"Algorithms for serial Filtering" \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtaxon_pair\fP"
.br
.RI "\fIDefines the next protein to work on. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef class \fBtaxon_pair\fP \fBtaxon_pair_t\fP"
.br
.RI "\fIDefines the next protein to work on. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Data container used for specific filtering operations. 
.SH "Typedef Documentation"
.PP 
.SS "typedef class \fBtaxon_pair\fP \fBtaxon_pair_t\fP"
.PP
Defines the next protein to work on. \fBAuthor:\fP
.RS 4
Ole Kristian Ekseth (oekseth) 
.RE
.PP
\fBDate:\fP
.RS 4
24.12.2011 by oekseth (removed calls to 'extern' variables to ease the inclusion of this class as a libary) 
.PP
31.12.2011 (cleanup) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for turboOrtho from the source code.
