.TH ""Filtering parsed Blast"" 3 "Sat Dec 31 2011" "Version 0.9.7.6" "turboOrtho" \" -*- nroff -*-
.ad l
.nh
.SH NAME
"Filtering parsed Blast" \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBblast_filtering\fP"
.br
.RI "\fIProduces a filtered output of the input. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBblast_filtering_main.h\fP"
.br
.PP

.RI "\fIThe launcher of the filtering library. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef class \fBblast_filtering\fP \fBblast_filtering_t\fP"
.br
.RI "\fIProduces a filtered output of the input. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Executing code for filtering 
.SH "Typedef Documentation"
.PP 
.SS "typedef class \fBblast_filtering\fP \fBblast_filtering_t\fP"
.PP
Produces a filtered output of the input. \fBAuthor:\fP
.RS 4
Ole Kristian Ekseth (oekseth) 
.RE
.PP
\fBDate:\fP
.RS 4
31.12.2011 by oekseth (clean-up) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for turboOrtho from the source code.
