.TH "pipe_norm.h" 3 "Sat Dec 31 2011" "Version 0.9.7.6" "turboOrtho" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pipe_norm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '../configure.h'\fP
.br
\fC#include 'types.h'\fP
.br
\fC#include 'log_builder.h'\fP
.br
\fC#include 'taxa.h'\fP
.br
\fC#include 'pipe_t.h'\fP
.br
\fC#include 'bucket_norm.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpipe_norm\fP"
.br
.RI "\fIUpdates an norm_t** object, if it's not done so in a previous phase. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for turboOrtho from the source code.
