.TH "pipe_write.h" 3 "Sat Dec 31 2011" "Version 0.9.7.6" "turboOrtho" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pipe_write.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'log_builder.h'\fP
.br
\fC#include 'types.h'\fP
.br
\fC#include 'libs.h'\fP
.br
\fC#include 'taxa.h'\fP
.br
\fC#include 'file_struct.h'\fP
.br
\fC#include 'build_string.h'\fP
.br
\fC#include 'bucket_norm.h'\fP
.br
\fC#include 'mcl_format.h'\fP
.br
\fC#include 'enum_mcl.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpipe_write\fP"
.br
.RI "\fIBuilds (writes) the result files, consisting of the strings given. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for turboOrtho from the source code.
