.TH "pipe_norm" 3 "Sat Dec 31 2011" "Version 0.9.7.6" "turboOrtho" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pipe_norm \- 
.PP
Updates an norm_t** object, if it's not done so in a previous phase.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pipe_norm.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void * \fBoperator()\fP (void *item)"
.br
.RI "\fIThe method of parallisation. \fP"
.ti -1c
.RI "\fBpipe_norm\fP (uint _taxon_length, const bool _use_everyrel_as_arrnorm_basis, const pipe_t type, log_builder_t *_log)"
.br
.RI "\fIThe constructor: \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "norm_t ** \fBarrNorm\fP"
.br
.RI "\fIThe object containing the basis for the normalization procedure. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Updates an norm_t** object, if it's not done so in a previous phase. 

\fBTodo\fP
.RS 4
If the norm_t** object is already up to data, this step is a waste of time. Consider using an altnerative approach. 
.RE
.PP
\fBAuthor:\fP
.RS 4
Ole Kristian Ekseth (oekseth) 
.RE
.PP
\fBDate:\fP
.RS 4
21.12.2010 by oekseth (initial) 
.PP
16.09.2011 by oekseth (asserts) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for turboOrtho from the source code.
