.TH ""Parallel filtering algorithms"" 3 "Sat Dec 31 2011" "Version 0.9.7.6" "turboOrtho" \" -*- nroff -*-
.ad l
.nh
.SH NAME
"Parallel filtering algorithms" \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBpipe_binary\fP"
.br
.RI "\fIFilters orthologs- and inparalogs in parallel. \fP"
.ti -1c
.RI "class \fBpipe_bucket\fP"
.br
.RI "\fIProduces buckets of numbered items to parse. \fP"
.ti -1c
.RI "class \fBpipe_merge\fP"
.br
.RI "\fIMerges containers building a filtered set of orthologs- and inparalogs. \fP"
.ti -1c
.RI "class \fBpipe_norm\fP"
.br
.RI "\fIUpdates an norm_t** object, if it's not done so in a previous phase. \fP"
.ti -1c
.RI "class \fBpipe_struct\fP"
.br
.RI "\fIEither builds co-orthologs or builds the strings for the result file. \fP"
.ti -1c
.RI "class \fBpipe_write\fP"
.br
.RI "\fIBuilds (writes) the result files, consisting of the strings given. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBblast_filtering_main.h\fP"
.br
.PP

.RI "\fIThe launcher of the filtering library. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Parallel blocks used during the filtering- and output process. 
.SH "Author"
.PP 
Generated automatically by Doxygen for turboOrtho from the source code.
