.TH "todo" 3 "Sat Dec 31 2011" "Version 0.9.7.6" "turboOrtho" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBClass \fBpipe_bucket\fP \fP" 1c
Should be considered removed, replaced by preestimated blocks used by each of the consquative threads 
.PP
.PP
 
.IP "\fBClass \fBpipe_norm\fP \fP" 1c
If the norm_t** object is already up to data, this step is a waste of time. Consider using an altnerative approach. 
.PP

