# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/klatremus/Dokumenter/Work/code/orthAgogue/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/klatremus/Dokumenter/Work/code/orthAgogue/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/klatremus/Dokumenter/Work/code/orthAgogue/src/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/klatremus/Dokumenter/Work/code/orthAgogue/src/CMakeFiles /home/klatremus/Dokumenter/Work/code/orthAgogue/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/klatremus/Dokumenter/Work/code/orthAgogue/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named orthAgogue

# Build rule for target.
orthAgogue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orthAgogue
.PHONY : orthAgogue

# fast build rule for target.
orthAgogue/fast:
	$(MAKE) -f CMakeFiles/orthAgogue.dir/build.make CMakeFiles/orthAgogue.dir/build
.PHONY : orthAgogue/fast

#=============================================================================
# Target rules for targets named orthAgogue-lib

# Build rule for target.
orthAgogue-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orthAgogue-lib
.PHONY : orthAgogue-lib

# fast build rule for target.
orthAgogue-lib/fast:
	$(MAKE) -f CMakeFiles/orthAgogue-lib.dir/build.make CMakeFiles/orthAgogue-lib.dir/build
.PHONY : orthAgogue-lib/fast

#=============================================================================
# Target rules for targets named algo_overlap

# Build rule for target.
algo_overlap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 algo_overlap
.PHONY : algo_overlap

# fast build rule for target.
algo_overlap/fast:
	$(MAKE) -f blast_common/CMakeFiles/algo_overlap.dir/build.make blast_common/CMakeFiles/algo_overlap.dir/build
.PHONY : algo_overlap/fast

#=============================================================================
# Target rules for targets named blast_common

# Build rule for target.
blast_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blast_common
.PHONY : blast_common

# fast build rule for target.
blast_common/fast:
	$(MAKE) -f blast_common/CMakeFiles/blast_common.dir/build.make blast_common/CMakeFiles/blast_common.dir/build
.PHONY : blast_common/fast

#=============================================================================
# Target rules for targets named blast_memory

# Build rule for target.
blast_memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blast_memory
.PHONY : blast_memory

# fast build rule for target.
blast_memory/fast:
	$(MAKE) -f blast_common/CMakeFiles/blast_memory.dir/build.make blast_common/CMakeFiles/blast_memory.dir/build
.PHONY : blast_memory/fast

#=============================================================================
# Target rules for targets named file_parse

# Build rule for target.
file_parse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file_parse
.PHONY : file_parse

# fast build rule for target.
file_parse/fast:
	$(MAKE) -f blast_common/CMakeFiles/file_parse.dir/build.make blast_common/CMakeFiles/file_parse.dir/build
.PHONY : file_parse/fast

#=============================================================================
# Target rules for targets named id_simil_list

# Build rule for target.
id_simil_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 id_simil_list
.PHONY : id_simil_list

# fast build rule for target.
id_simil_list/fast:
	$(MAKE) -f blast_common/CMakeFiles/id_simil_list.dir/build.make blast_common/CMakeFiles/id_simil_list.dir/build
.PHONY : id_simil_list/fast

#=============================================================================
# Target rules for targets named index

# Build rule for target.
index: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 index
.PHONY : index

# fast build rule for target.
index/fast:
	$(MAKE) -f blast_common/CMakeFiles/index.dir/build.make blast_common/CMakeFiles/index.dir/build
.PHONY : index/fast

#=============================================================================
# Target rules for targets named index_list

# Build rule for target.
index_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 index_list
.PHONY : index_list

# fast build rule for target.
index_list/fast:
	$(MAKE) -f blast_common/CMakeFiles/index_list.dir/build.make blast_common/CMakeFiles/index_list.dir/build
.PHONY : index_list/fast

#=============================================================================
# Target rules for targets named list_file_chunk

# Build rule for target.
list_file_chunk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 list_file_chunk
.PHONY : list_file_chunk

# fast build rule for target.
list_file_chunk/fast:
	$(MAKE) -f blast_common/CMakeFiles/list_file_chunk.dir/build.make blast_common/CMakeFiles/list_file_chunk.dir/build
.PHONY : list_file_chunk/fast

#=============================================================================
# Target rules for targets named list_file_parse

# Build rule for target.
list_file_parse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 list_file_parse
.PHONY : list_file_parse

# fast build rule for target.
list_file_parse/fast:
	$(MAKE) -f blast_common/CMakeFiles/list_file_parse.dir/build.make blast_common/CMakeFiles/list_file_parse.dir/build
.PHONY : list_file_parse/fast

#=============================================================================
# Target rules for targets named list_norm

# Build rule for target.
list_norm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 list_norm
.PHONY : list_norm

# fast build rule for target.
list_norm/fast:
	$(MAKE) -f blast_common/CMakeFiles/list_norm.dir/build.make blast_common/CMakeFiles/list_norm.dir/build
.PHONY : list_norm/fast

#=============================================================================
# Target rules for targets named mcl_bunch

# Build rule for target.
mcl_bunch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcl_bunch
.PHONY : mcl_bunch

# fast build rule for target.
mcl_bunch/fast:
	$(MAKE) -f blast_common/CMakeFiles/mcl_bunch.dir/build.make blast_common/CMakeFiles/mcl_bunch.dir/build
.PHONY : mcl_bunch/fast

#=============================================================================
# Target rules for targets named mcl_format

# Build rule for target.
mcl_format: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcl_format
.PHONY : mcl_format

# fast build rule for target.
mcl_format/fast:
	$(MAKE) -f blast_common/CMakeFiles/mcl_format.dir/build.make blast_common/CMakeFiles/mcl_format.dir/build
.PHONY : mcl_format/fast

#=============================================================================
# Target rules for targets named mpi_read

# Build rule for target.
mpi_read: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpi_read
.PHONY : mpi_read

# fast build rule for target.
mpi_read/fast:
	$(MAKE) -f blast_common/CMakeFiles/mpi_read.dir/build.make blast_common/CMakeFiles/mpi_read.dir/build
.PHONY : mpi_read/fast

#=============================================================================
# Target rules for targets named norm_t

# Build rule for target.
norm_t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 norm_t
.PHONY : norm_t

# fast build rule for target.
norm_t/fast:
	$(MAKE) -f blast_common/CMakeFiles/norm_t.dir/build.make blast_common/CMakeFiles/norm_t.dir/build
.PHONY : norm_t/fast

#=============================================================================
# Target rules for targets named orthAgogue-memory-lib

# Build rule for target.
orthAgogue-memory-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orthAgogue-memory-lib
.PHONY : orthAgogue-memory-lib

# fast build rule for target.
orthAgogue-memory-lib/fast:
	$(MAKE) -f blast_common/CMakeFiles/orthAgogue-memory-lib.dir/build.make blast_common/CMakeFiles/orthAgogue-memory-lib.dir/build
.PHONY : orthAgogue-memory-lib/fast

#=============================================================================
# Target rules for targets named p_rel

# Build rule for target.
p_rel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p_rel
.PHONY : p_rel

# fast build rule for target.
p_rel/fast:
	$(MAKE) -f blast_common/CMakeFiles/p_rel.dir/build.make blast_common/CMakeFiles/p_rel.dir/build
.PHONY : p_rel/fast

#=============================================================================
# Target rules for targets named parse

# Build rule for target.
parse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parse
.PHONY : parse

# fast build rule for target.
parse/fast:
	$(MAKE) -f blast_common/CMakeFiles/parse.dir/build.make blast_common/CMakeFiles/parse.dir/build
.PHONY : parse/fast

#=============================================================================
# Target rules for targets named prot_list

# Build rule for target.
prot_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prot_list
.PHONY : prot_list

# fast build rule for target.
prot_list/fast:
	$(MAKE) -f blast_common/CMakeFiles/prot_list.dir/build.make blast_common/CMakeFiles/prot_list.dir/build
.PHONY : prot_list/fast

#=============================================================================
# Target rules for targets named protein_relation

# Build rule for target.
protein_relation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protein_relation
.PHONY : protein_relation

# fast build rule for target.
protein_relation/fast:
	$(MAKE) -f blast_common/CMakeFiles/protein_relation.dir/build.make blast_common/CMakeFiles/protein_relation.dir/build
.PHONY : protein_relation/fast

#=============================================================================
# Target rules for targets named protein_vector

# Build rule for target.
protein_vector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protein_vector
.PHONY : protein_vector

# fast build rule for target.
protein_vector/fast:
	$(MAKE) -f blast_common/CMakeFiles/protein_vector.dir/build.make blast_common/CMakeFiles/protein_vector.dir/build
.PHONY : protein_vector/fast

#=============================================================================
# Target rules for targets named rel

# Build rule for target.
rel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rel
.PHONY : rel

# fast build rule for target.
rel/fast:
	$(MAKE) -f blast_common/CMakeFiles/rel.dir/build.make blast_common/CMakeFiles/rel.dir/build
.PHONY : rel/fast

#=============================================================================
# Target rules for targets named relations_list

# Build rule for target.
relations_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 relations_list
.PHONY : relations_list

# fast build rule for target.
relations_list/fast:
	$(MAKE) -f blast_common/CMakeFiles/relations_list.dir/build.make blast_common/CMakeFiles/relations_list.dir/build
.PHONY : relations_list/fast

#=============================================================================
# Target rules for targets named taxa

# Build rule for target.
taxa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 taxa
.PHONY : taxa

# fast build rule for target.
taxa/fast:
	$(MAKE) -f blast_common/CMakeFiles/taxa.dir/build.make blast_common/CMakeFiles/taxa.dir/build
.PHONY : taxa/fast

#=============================================================================
# Target rules for targets named x_blast_common

# Build rule for target.
x_blast_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 x_blast_common
.PHONY : x_blast_common

# fast build rule for target.
x_blast_common/fast:
	$(MAKE) -f blast_common/CMakeFiles/x_blast_common.dir/build.make blast_common/CMakeFiles/x_blast_common.dir/build
.PHONY : x_blast_common/fast

#=============================================================================
# Target rules for targets named log_builder

# Build rule for target.
log_builder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 log_builder
.PHONY : log_builder

# fast build rule for target.
log_builder/fast:
	$(MAKE) -f log_builder/CMakeFiles/log_builder.dir/build.make log_builder/CMakeFiles/log_builder.dir/build
.PHONY : log_builder/fast

#=============================================================================
# Target rules for targets named x_log_builder

# Build rule for target.
x_log_builder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 x_log_builder
.PHONY : x_log_builder

# fast build rule for target.
x_log_builder/fast:
	$(MAKE) -f log_builder/CMakeFiles/x_log_builder.dir/build.make log_builder/CMakeFiles/x_log_builder.dir/build
.PHONY : x_log_builder/fast

#=============================================================================
# Target rules for targets named blast_terminal

# Build rule for target.
blast_terminal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blast_terminal
.PHONY : blast_terminal

# fast build rule for target.
blast_terminal/fast:
	$(MAKE) -f terminal_input/CMakeFiles/blast_terminal.dir/build.make terminal_input/CMakeFiles/blast_terminal.dir/build
.PHONY : blast_terminal/fast

#=============================================================================
# Target rules for targets named cmd_argument

# Build rule for target.
cmd_argument: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmd_argument
.PHONY : cmd_argument

# fast build rule for target.
cmd_argument/fast:
	$(MAKE) -f terminal_input/CMakeFiles/cmd_argument.dir/build.make terminal_input/CMakeFiles/cmd_argument.dir/build
.PHONY : cmd_argument/fast

#=============================================================================
# Target rules for targets named cmd_line

# Build rule for target.
cmd_line: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmd_line
.PHONY : cmd_line

# fast build rule for target.
cmd_line/fast:
	$(MAKE) -f terminal_input/CMakeFiles/cmd_line.dir/build.make terminal_input/CMakeFiles/cmd_line.dir/build
.PHONY : cmd_line/fast

#=============================================================================
# Target rules for targets named cmd_list

# Build rule for target.
cmd_list: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmd_list
.PHONY : cmd_list

# fast build rule for target.
cmd_list/fast:
	$(MAKE) -f terminal_input/CMakeFiles/cmd_list.dir/build.make terminal_input/CMakeFiles/cmd_list.dir/build
.PHONY : cmd_list/fast

#=============================================================================
# Target rules for targets named x_terminal

# Build rule for target.
x_terminal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 x_terminal
.PHONY : x_terminal

# fast build rule for target.
x_terminal/fast:
	$(MAKE) -f terminal_input/CMakeFiles/x_terminal.dir/build.make terminal_input/CMakeFiles/x_terminal.dir/build
.PHONY : x_terminal/fast

#=============================================================================
# Target rules for targets named blast_parsing

# Build rule for target.
blast_parsing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blast_parsing
.PHONY : blast_parsing

# fast build rule for target.
blast_parsing/fast:
	$(MAKE) -f blast_parsing/CMakeFiles/blast_parsing.dir/build.make blast_parsing/CMakeFiles/blast_parsing.dir/build
.PHONY : blast_parsing/fast

#=============================================================================
# Target rules for targets named blast_parsing_m

# Build rule for target.
blast_parsing_m: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blast_parsing_m
.PHONY : blast_parsing_m

# fast build rule for target.
blast_parsing_m/fast:
	$(MAKE) -f blast_parsing/CMakeFiles/blast_parsing_m.dir/build.make blast_parsing/CMakeFiles/blast_parsing_m.dir/build
.PHONY : blast_parsing_m/fast

#=============================================================================
# Target rules for targets named orthAgogue-parse-lib

# Build rule for target.
orthAgogue-parse-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orthAgogue-parse-lib
.PHONY : orthAgogue-parse-lib

# fast build rule for target.
orthAgogue-parse-lib/fast:
	$(MAKE) -f blast_parsing/CMakeFiles/orthAgogue-parse-lib.dir/build.make blast_parsing/CMakeFiles/orthAgogue-parse-lib.dir/build
.PHONY : orthAgogue-parse-lib/fast

#=============================================================================
# Target rules for targets named x_blast_parsing

# Build rule for target.
x_blast_parsing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 x_blast_parsing
.PHONY : x_blast_parsing

# fast build rule for target.
x_blast_parsing/fast:
	$(MAKE) -f blast_parsing/CMakeFiles/x_blast_parsing.dir/build.make blast_parsing/CMakeFiles/x_blast_parsing.dir/build
.PHONY : x_blast_parsing/fast

#=============================================================================
# Target rules for targets named blast_filtering

# Build rule for target.
blast_filtering: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blast_filtering
.PHONY : blast_filtering

# fast build rule for target.
blast_filtering/fast:
	$(MAKE) -f blast_filtering/CMakeFiles/blast_filtering.dir/build.make blast_filtering/CMakeFiles/blast_filtering.dir/build
.PHONY : blast_filtering/fast

#=============================================================================
# Target rules for targets named blast_filtering_m

# Build rule for target.
blast_filtering_m: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blast_filtering_m
.PHONY : blast_filtering_m

# fast build rule for target.
blast_filtering_m/fast:
	$(MAKE) -f blast_filtering/CMakeFiles/blast_filtering_m.dir/build.make blast_filtering/CMakeFiles/blast_filtering_m.dir/build
.PHONY : blast_filtering_m/fast

#=============================================================================
# Target rules for targets named orthAgogue-filter-lib

# Build rule for target.
orthAgogue-filter-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 orthAgogue-filter-lib
.PHONY : orthAgogue-filter-lib

# fast build rule for target.
orthAgogue-filter-lib/fast:
	$(MAKE) -f blast_filtering/CMakeFiles/orthAgogue-filter-lib.dir/build.make blast_filtering/CMakeFiles/orthAgogue-filter-lib.dir/build
.PHONY : orthAgogue-filter-lib/fast

#=============================================================================
# Target rules for targets named x_blast_filtering

# Build rule for target.
x_blast_filtering: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 x_blast_filtering
.PHONY : x_blast_filtering

# fast build rule for target.
x_blast_filtering/fast:
	$(MAKE) -f blast_filtering/CMakeFiles/x_blast_filtering.dir/build.make blast_filtering/CMakeFiles/x_blast_filtering.dir/build
.PHONY : x_blast_filtering/fast

orthAgogue_main.o: orthAgogue_main.cxx.o
.PHONY : orthAgogue_main.o

# target to build an object file
orthAgogue_main.cxx.o:
	$(MAKE) -f CMakeFiles/orthAgogue.dir/build.make CMakeFiles/orthAgogue.dir/orthAgogue_main.cxx.o
	$(MAKE) -f CMakeFiles/orthAgogue-lib.dir/build.make CMakeFiles/orthAgogue-lib.dir/orthAgogue_main.cxx.o
.PHONY : orthAgogue_main.cxx.o

orthAgogue_main.i: orthAgogue_main.cxx.i
.PHONY : orthAgogue_main.i

# target to preprocess a source file
orthAgogue_main.cxx.i:
	$(MAKE) -f CMakeFiles/orthAgogue.dir/build.make CMakeFiles/orthAgogue.dir/orthAgogue_main.cxx.i
	$(MAKE) -f CMakeFiles/orthAgogue-lib.dir/build.make CMakeFiles/orthAgogue-lib.dir/orthAgogue_main.cxx.i
.PHONY : orthAgogue_main.cxx.i

orthAgogue_main.s: orthAgogue_main.cxx.s
.PHONY : orthAgogue_main.s

# target to generate assembly for a file
orthAgogue_main.cxx.s:
	$(MAKE) -f CMakeFiles/orthAgogue.dir/build.make CMakeFiles/orthAgogue.dir/orthAgogue_main.cxx.s
	$(MAKE) -f CMakeFiles/orthAgogue-lib.dir/build.make CMakeFiles/orthAgogue-lib.dir/orthAgogue_main.cxx.s
.PHONY : orthAgogue_main.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... orthAgogue"
	@echo "... orthAgogue-lib"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... algo_overlap"
	@echo "... blast_common"
	@echo "... blast_memory"
	@echo "... file_parse"
	@echo "... id_simil_list"
	@echo "... index"
	@echo "... index_list"
	@echo "... list_file_chunk"
	@echo "... list_file_parse"
	@echo "... list_norm"
	@echo "... mcl_bunch"
	@echo "... mcl_format"
	@echo "... mpi_read"
	@echo "... norm_t"
	@echo "... orthAgogue-memory-lib"
	@echo "... p_rel"
	@echo "... parse"
	@echo "... prot_list"
	@echo "... protein_relation"
	@echo "... protein_vector"
	@echo "... rel"
	@echo "... relations_list"
	@echo "... taxa"
	@echo "... x_blast_common"
	@echo "... log_builder"
	@echo "... x_log_builder"
	@echo "... blast_terminal"
	@echo "... cmd_argument"
	@echo "... cmd_line"
	@echo "... cmd_list"
	@echo "... x_terminal"
	@echo "... blast_parsing"
	@echo "... blast_parsing_m"
	@echo "... orthAgogue-parse-lib"
	@echo "... x_blast_parsing"
	@echo "... blast_filtering"
	@echo "... blast_filtering_m"
	@echo "... orthAgogue-filter-lib"
	@echo "... x_blast_filtering"
	@echo "... orthAgogue_main.o"
	@echo "... orthAgogue_main.i"
	@echo "... orthAgogue_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

